POST http://localhost:4000/delete_writing
content-type: application/json

{
    "id":"test8",
    "content":"랴ㅕ여오",
    "date":"2021-05-04",
    "cosmeticNameDB":"나나나" 
}
###

POST http://localhost:4000/search_writing
content-type: application/json

{
    "title":"lolo"
}
###
POST http://localhost:4000/search_cosmetic
content-type: application/json

{
    "name":"sung"
}

###
POST https://91e3db492378.ngrok.io/register
content-type: application/json

{
    "id":"test9",
    "password":"pw9",
    "name":"name9",
    "email":"test9@email.com"
}

###

POST http://localhost:4000/login
content-type: application/json

{
	"id": "test8",
    "password" :"pw8"
}

###

POST http://localhost:4000/dupCheck
content-type: application/json

{
    "id":"test9"
}

###

GET  https://847a194b5fdb.ngrok.io/374.jpg
content-type: application/json

{
}

###
POST  http://localhost:4000/search_cosmetic
content-type: application/json

{
    "name":"sung"
}

###
POST http://localhost:4000/register
content-type: application/json

{
    "id":"test8",
    "password":"pw8",
    "name":"name8",
    "email":"test8@email.com"
}

###

POST http://localhost:4000/login
content-type: application/json

{
	"id": "test8",
    "password" :"pw8"
}

###

POST http://localhost:4000/dupCheck
content-type: application/json

{
    "id":"test9"
}

###

GET http://localhost:4000
content-type: application/json

{
    # "id": "sm10@example.com",
    # "password" :"pa"
}
